# Generated by Django 5.0 on 2024-10-03 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PersonInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateField(auto_now_add=True, null=True)),
                ('last_updated_date', models.DateField(auto_now=True, null=True)),
                ('name', models.CharField(max_length=256, verbose_name='Нэр')),
                ('person_image', models.ImageField(blank=True, null=True, upload_to='midsite/person-information', verbose_name='Зураг')),
                ('bio', models.TextField(verbose_name='bio')),
                ('phone', models.IntegerField(max_length=8, verbose_name='Утасны дугаар')),
                ('gmail', models.CharField(max_length=100, verbose_name='Gmail')),
            ],
            options={
                'verbose_name': 'Person information',
                'verbose_name_plural': 'Person information',
            },
        ),
    ]
