# Generated by Django 5.0 on 2024-10-03 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personinfo',
            name='phone',
            field=models.IntegerField(verbose_name='Утасны дугаар'),
        ),
    ]
