# Generated by Django 5.0 on 2024-10-16 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_register'),
    ]

    operations = [
        migrations.AddField(
            model_name='register',
            name='password',
            field=models.IntegerField(blank=True, max_length=30, null=True, verbose_name='password'),
        ),
        migrations.AlterField(
            model_name='register',
            name='email',
            field=models.EmailField(blank=True, max_length=255, null=True, verbose_name='И-мэйл*'),
        ),
        migrations.AlterField(
            model_name='register',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Нэр*'),
        ),
        migrations.AlterField(
            model_name='register',
            name='phone',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Утасны дугаар*'),
        ),
    ]
