# Generated by Django 5.0 on 2024-10-16 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_register_password_alter_register_email_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='personinfo',
            name='gmail',
        ),
        migrations.RemoveField(
            model_name='register',
            name='name',
        ),
        migrations.AddField(
            model_name='personinfo',
            name='email',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Gmail'),
        ),
        migrations.AddField(
            model_name='register',
            name='username',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Нэр*'),
        ),
        migrations.AlterField(
            model_name='register',
            name='password',
            field=models.IntegerField(blank=True, max_length=128, null=True, verbose_name='password'),
        ),
    ]
