# Generated by Django 5.0 on 2024-10-16 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_remove_personinfo_gmail_remove_register_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='register',
            name='password',
            field=models.IntegerField(blank=True, null=True, verbose_name='password'),
        ),
    ]
