# Generated by Django 5.0 on 2024-10-16 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_register_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='register',
            name='password',
            field=models.CharField(blank=True, max_length=400, null=True, verbose_name='password'),
        ),
    ]
