# Generated by Django 5.0 on 2024-10-17 17:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_register_password'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='personinfo',
            name='created_date',
        ),
        migrations.RemoveField(
            model_name='personinfo',
            name='last_updated_date',
        ),
        migrations.AddField(
            model_name='personinfo',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='person_info', to='core.register'),
        ),
    ]
