# Generated by Django 5.0 on 2025-01-08 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_remove_personinfo_created_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game_name', models.CharField(max_length=256, verbose_name='Нэр')),
                ('game_img', models.ImageField(blank=True, null=True, upload_to='midsite/home/game_info', verbose_name='Зураг')),
                ('game_details', models.TextField(blank=True, null=True, verbose_name='Заавар')),
                ('download_link', models.URLField(blank=True, null=True, verbose_name='Тоглоомны холбоос')),
            ],
            options={
                'verbose_name': 'Game',
                'verbose_name_plural': 'Games',
            },
        ),
    ]
