# Generated by Django 5.1.5 on 2025-02-04 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_game'),
    ]

    operations = [
        migrations.CreateModel(
            name='Software',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256, verbose_name='Гарчиг')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Тайлбар')),
                ('img', models.ImageField(blank=True, null=True, upload_to='midsite/home/software', verbose_name='Зураг')),
            ],
            options={
                'verbose_name': 'Softwares',
            },
        ),
    ]
