# Generated by Django 5.1.5 on 2025-02-04 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_software'),
    ]

    operations = [
        migrations.AddField(
            model_name='software',
            name='link',
            field=models.URLField(blank=True, null=True, verbose_name='Үсрэх url'),
        ),
    ]
