# Generated by Django 5.2.4 on 2025-10-28 12:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_software_link'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='software',
            options={'verbose_name': 'Software', 'verbose_name_plural': 'Softwares'},
        ),
    ]
