# Generated by Django 5.2.4 on 2025-11-05 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_alter_software_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportOffer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=256, verbose_name='user name')),
                ('user_report', models.TextField(blank=True, null=True, verbose_name='user_reported')),
                ('user_proof', models.ImageField(blank=True, null=True, upload_to='midsite/home/report', verbose_name='user_proof')),
                ('reported_page', models.URLField(blank=True, null=True, verbose_name='reported_page_url')),
            ],
            options={
                'verbose_name': 'user_report',
                'verbose_name_plural': 'user_reports',
            },
        ),
    ]
